#!/usr/bin/env python3
"""Single source of the registry counts. Counts are measured, never typed.

Every README in this repository has, at some point, asserted a count that later
stopped being true. `.claude/README.md` once disagreed with itself four lines
apart, across at least two commits. The failure mode is not carelessness: a
count in prose sounds authoritative, which is exactly what stops the next reader
re-checking it.

So no document states a count in prose any more. Each carries a generated block
between markers, this tool regenerates it, and CI fails on any diff.

    python sdlc-suite/tools/counts.py            # print the table
    python sdlc-suite/tools/counts.py --write    # rewrite every marked block
    python sdlc-suite/tools/counts.py --check    # exit non-zero if any block is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

START = "<!-- counts:start -->"
END = "<!-- counts:end -->"

GENERATED_NOTE = (
    "*Generated by `sdlc-suite/tools/counts.py`. Do not edit by hand — "
    "CI fails on any diff. The table below owns these numbers; no prose "
    "elsewhere should restate them.*"
)

# Agent file extension per tree. `.agents/` ships skills only and has no agents
# directory; that is deliberate, not a gap, so it is recorded as absent rather
# than counted as zero-of-twenty-two.
TREES = [
    (".claude/", ".md"),
    ("sdlc-suite/", ".md"),
    ("commandcode-suite/", ".md"),
    (".kimi-code/", ".md"),
    (".copilot/", ".json"),
    (".codex/", ".toml"),
    (".agents/", None),
]

# Documents that carry a generated block. Adding a document here is all that is
# needed for CI to start checking it.
DOCUMENTS = [
    "README.md",
    ".claude/README.md",
    "sdlc-suite/README.md",
    "commandcode-suite/README.md",
]


def _count_files(directory: Path, suffix: str) -> int | None:
    if not directory.is_dir():
        return None
    return sum(1 for p in directory.iterdir() if p.is_file() and p.suffix == suffix)


def _count_dirs(directory: Path) -> int | None:
    if not directory.is_dir():
        return None
    return sum(1 for p in directory.iterdir() if p.is_dir())


# Shared modules that are not workflows despite lacking the `_` prefix. The
# JS trees use `_runner.js`; the Python port called the same thing `runner.py`.
# That inconsistency is real, so it is named here rather than papered over by a
# heuristic that would silently miscount the day someone adds `helpers.py`.
SHARED_MODULE_NAMES = {"runner.py"}


def _count_workflows(directory: Path) -> int | None:
    """Runnable workflows only.

    A leading underscore marks a shared module, not a workflow — `_runner.js`,
    `_state.js`, `_policy.js`. Counting those inflates the number and is how
    "6 workflows" became "8" without anyone adding one.
    """
    if not directory.is_dir():
        return None
    return sum(
        1
        for p in directory.iterdir()
        if p.is_file()
        and p.suffix in (".js", ".py", ".mjs")
        and not p.name.startswith("_")
        and p.name not in SHARED_MODULE_NAMES
    )


def measure() -> list[dict]:
    rows = []
    for tree, agent_ext in TREES:
        base = ROOT / tree.rstrip("/")
        rows.append(
            {
                "tree": tree,
                "agents": _count_files(base / "agents", agent_ext) if agent_ext else None,
                "skills": _count_dirs(base / "skills"),
                "workflows": _count_workflows(base / "workflows"),
                "commands": _count_files(base / "commands", ".md"),
            }
        )
    return rows


def _cell(value: int | None) -> str:
    return "—" if value is None else str(value)


def render() -> str:
    rows = measure()
    lines = [
        START,
        GENERATED_NOTE,
        "",
        "| Tree | Agents | Skills | Workflows | Commands |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['tree']}` | {_cell(r['agents'])} | {_cell(r['skills'])} "
            f"| {_cell(r['workflows'])} | {_cell(r['commands'])} |"
        )
    lines += [
        "",
        "`—` means the tree does not ship that artifact kind. `.agents/` is skills only.",
        "`.kimi-code/` skills include six workflow-launcher skills that exist only in that port.",
        END,
    ]
    return "\n".join(lines)


def _replace_block(text: str, block: str) -> tuple[str, bool]:
    """Return (new_text, found). Missing markers are a document problem, not ours."""
    start = text.find(START)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        return text, False
    return text[:start] + block + text[end + len(END):], True


def main() -> int:
    # The generated block contains em-dashes. On Windows the default console
    # encoding is cp1252, which mangles them on print even though the file
    # write below is explicitly UTF-8 — so a human reading the terminal would
    # see different bytes from the ones CI compares.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="rewrite every marked block")
    group.add_argument("--check", action="store_true", help="exit non-zero if any block is stale")
    args = ap.parse_args()

    block = render()

    if not args.write and not args.check:
        print(block)
        return 0

    stale: list[str] = []
    missing: list[str] = []
    written: list[str] = []

    for rel in DOCUMENTS:
        path = ROOT / rel
        if not path.is_file():
            missing.append(f"{rel}: file not found")
            continue
        # newline="" preserves whatever the file already uses on read; the write
        # below pins LF explicitly, because a converter or an editor writing
        # CRLF into a definition is the failure this repository already hit.
        original = path.read_text(encoding="utf-8")
        updated, found = _replace_block(original, block)
        if not found:
            missing.append(f"{rel}: no {START} / {END} markers")
            continue
        if updated == original:
            continue
        if args.check:
            stale.append(rel)
        else:
            path.write_text(updated, encoding="utf-8", newline="\n")
            written.append(rel)

    if missing:
        for m in missing:
            print(f"FAIL: {m}", file=sys.stderr)
        return 1

    if args.check:
        if stale:
            for rel in stale:
                print(f"FAIL: {rel} counts block is stale — run counts.py --write", file=sys.stderr)
            return 1
        print(f"OK: {len(DOCUMENTS)} documents match the tree")
        return 0

    if written:
        for rel in written:
            print(f"[updated] {rel}")
    else:
        print("[unchanged] all documents already match the tree")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
